/*************************************************************************//*!
					
					@file	MofID.h
					@brief	内部クラスＩＤの定義

															@author	CDW
															@date	2014.05.14
*//**************************************************************************/

//ONCE
#ifndef		__MOFID__H__

#define		__MOFID__H__

/*************************************************************************//*!
					ID設定基礎
*//**************************************************************************/
#define		MOF_CLASSBASEINTERFACE								0x8000																	//!<基底インターフェイス
#define		MOF_CLASSIDSET(parent,id)							(((parent & 0xFFFF) << 16) | id)										//!<クラスIDの作成
#define		MOF_PARENTCLASS_ID(id)								((id >> 16) & 0xFFFF)													//!<IDから派生元クラスIDを取り出す
#define		MOF_ISPARENTCLASS(id1,id2)							((((id2 & 0xFFFF) == (MOF_PARENTCLASS_ID(id1))) ? TRUE : FALSE))		//!<id1の派生元クラスがid2か調べる

/*************************************************************************//*!
					汎用処理関連内部ID
*//**************************************************************************/
#define		MOF_SMARTPOINTERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0103)			//!<スマートポインタクラス
#define		MOF_ASTRINGCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0104)			//!<マルチバイト文字列クラス
#define		MOF_WSTRINGCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0105)			//!<UNICODE文字列クラス
#define		MOF_ALLOCATORCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0106)			//!<メモリ確保クラス
#define		MOF_DYNAMICARRAYCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0107)			//!<動的配列クラス
#define		MOF_READTEXTFILECLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0108)			//!<テキストファイル入力クラス
#define		MOF_READBINARYFILECLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0109)			//!<バイナリファイル入力クラス
#define		MOF_WRITETEXTFILECLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x010A)			//!<テキストファイル出力クラス
#define		MOF_WRITEBINARYFILECLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x010B)			//!<バイナリファイル出力クラス
#define		MOF_ENCRYPTFILECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x010C)			//!<ファイル暗号化クラス
#define		MOF_DECRYPTFILECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x010D)			//!<ファイル複合化クラス
#define		MOF_WRITECHUNKFILECLASS_ID									MOF_CLASSIDSET(MOF_WRITEBINARYFILECLASS_ID,		0x010E)			//!<チャンク管理ファイル出力クラス
#define		MOF_PACKFILECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x010F)			//!<パックファイルクラス
#define		MOF_KEYFRAMECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0110)			//!<キーフレームクラス
#define		MOF_KEYFRAMEARRAYCLASS_ID									MOF_CLASSIDSET(MOF_DYNAMICARRAYCLASS_ID,		0x0111)			//!<キーフレームクラス
#define		MOF_LOCKCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0112)			//!<ロッククラス
#define		MOF_SEMAPHORECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0113)			//!<ロッククラス
#define		MOF_FOCUSLOCKCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0114)			//!<ロッククラス
#define		MOF_QUEUECLASS_ID											MOF_CLASSIDSET(MOF_DYNAMICARRAYCLASS_ID,		0x0115)			//!<キュークラス
#define		MOF_THREADCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0116)			//!スレッドクラス
#define		MOF_RUNNABLECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0117)			//!スレッド内部実装
#define		MOF_RUNNABLETHREADCLASS_ID									MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x0118)			//!スレッド内部実装実行
#define		MOF_CALLBACKTHREADCLASS_ID									MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x0119)			//!スレッド内部実装実行
#define		MOF_WINSINGLEGAMEAPPLICATIONCLASS_ID						MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x011A)			//!ゲーム更新内部実装
#define		MOF_UWPGAMEAPPLICATIONCLASS_ID								MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x011A)			//!ゲーム更新内部実装
#define		MOF_WINMULTIGAMEAPPLICATIONCLASS_ID							MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x011B)			//!ゲーム更新内部実装
#define		MOF_ANDROIDSINGLEGAMEAPPLICATIONCLASS_ID					MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x011C)			//!ゲーム更新内部実装

/*************************************************************************//*!
					算術処理関連内部ID
*//**************************************************************************/
#define		MOF_VECTOR2CLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0201)			//!<2Dベクトルクラス
#define		MOF_VECTOR3CLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0202)			//!<3Dベクトルクラス
#define		MOF_VECTOR4CLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0203)			//!<4Dベクトルクラス
#define		MOF_MATRIX33CLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0204)			//!<3×3行列クラス
#define		MOF_MATRIX44CLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0205)			//!<4×4行列クラス
#define		MOF_QUATERNIONCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0206)			//!<クオータニオンクラス
#define		MOF_RANDOMCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0207)			//!<ランダムクラス

/*************************************************************************//*!
					フレームワーク関連内部ID
*//**************************************************************************/
#define		MOF_WINDOWCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0301)			//!<ウインドウクラス
#define		MOF_DEFWINDOWPROCCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0302)			//!<ウインドウプロシージャクラス
#define		MOF_IMEWINDOWPROCCLASS_ID									MOF_CLASSIDSET(MOF_DEFWINDOWPROCCLASS_ID,		0x0303)			//!<ウインドウプロシージャクラス
#define		MOF_DX11GAMEFRAMEWORKCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0304)			//!<DX11フレームワーククラス
#define		MOF_DX12GAMEFRAMEWORKCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0304)			//!<DX12フレームワーククラス
#define		MOF_UWPGAMEFRAMEWORKCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0304)			//!<DX11フレームワーククラス
#define		MOF_ANDROIDJNIGAMEFRAMEWORKCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0305)			//!<AndroidJNIフレームワーククラス
#define		MOF_WINDOWSFRAMETIMERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0306)			//!<フレームタイマークラス
#define		MOF_UWPFRAMETIMERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0306)			//!<フレームタイマークラス
#define		MOF_ANDROIDFRAMETIMERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0307)			//!<フレームタイマークラス

/*************************************************************************//*!
					グラフィック関連内部ID
*//**************************************************************************/

//----------------------------------------------------------------------------
//共有グラフィックス

//基本処理
#define		MOF_CAMERACLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0400)			//!<カメラクラス
#define		MOF_DIRECTIONALLIGHTCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0401)			//!<方向光源クラス
#define		MOF_RENDERCOMMANDCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0402)			//!<描画コマンド
#define		MOF_RENDERCOMMANDLISTCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0403)			//!<描画コマンドリスト
#define		MOF_RENDERCOMMANDPROXYCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0404)			//!<描画コマンド
#define		MOF_RENDERTHREADCLASS_ID									MOF_CLASSIDSET(MOF_THREADCLASS_ID,				0x0405)			//!<描画スレッド

//スプライト
#define		MOF_SPRITE2DCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0410)			//!<2Dスプライトクラス
#define		MOF_SPRITE3DCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0411)			//!<3Dスプライトクラス
#define		MOF_SPRITE2DPARTCLASS_ID									MOF_CLASSIDSET(MOF_SPRITE2DCLASS_ID,			0x0412)			//!<2Dスプライトパーツ
#define		MOF_SPRITE2DCONTAINERCLASS_ID								MOF_CLASSIDSET(MOF_SPRITE2DPARTCLASS_ID,		0x0413)			//!<スプライトコンテナ
#define		MOF_SPRITE2DEFFECTCLASS_ID									MOF_CLASSIDSET(MOF_SPRITE2DPARTCLASS_ID,		0x0414)			//!<スプライトエフェクト
#define		MOF_SPRITEANIMATIONCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0415)			//!<スプライトアニメーションクラス
#define		MOF_SPRITEPARTANIMATIONCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0416)			//!<スプライトパーツアニメーションクラス
#define		MOF_SPRITECONTAINERANIMATIONCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0417)			//!<スプライトコンテナアニメーションクラス
#define		MOF_SPRITEMOTIONCONTROLLERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0418)			//!<スプライトアニメーションコントローラークラス
#define		MOF_ANALYSSPRITECLASS_ID									MOF_CLASSIDSET(MOF_READBINARYFILECLASS_ID,		0x0419)			//!<MOSファイル解析クラス
#define		MOF_SPRITEPARTMOTIONCONTROLLERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x041A)			//!<スプライトパーツアニメーションコントローラークラス

//メッシュ
#define		MOF_ANALYSMESHCLASS_ID										MOF_CLASSIDSET(MOF_READBINARYFILECLASS_ID,		0x0420)			//!<MOMファイル解析クラス
#define		MOF_WRITEMESHCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0421)			//!<MOMファイル保存クラス
#define		MOF_BONECLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0422)			//!<ボーンクラス
#define		MOF_MESHBONEANIMATIONCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0423)			//!<ボーンアニメーションクラス
#define		MOF_GEOMETRYMORPHINGANIMATIONCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0424)			//!<モーフィングクラス
#define		MOF_MESHMORPHINGANIMATIONCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0425)			//!<モーフィングアニメーションクラス
#define		MOF_MESHMOTIONCONTROLLERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0426)			//!<メッシュアニメーションコントローラークラス
#define		MOF_MESHANIMATIONCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0427)			//!<メッシュアニメーションクラス
#define		MOF_CCDIKJOINTCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0428)			//!<ＩＫクラス
#define		MOF_CCDIKCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0429)			//!<ＩＫクラス
#define		MOF_MESHCAMERACLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x042A)			//!<カメラクラス
#define		MOF_MESHCAMERAANIMATIONCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x042B)			//!<カメラアニメーションクラス

//メッシュ変換
#define		MOF_XMODELCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0430)			//!<Xファイルクラス
#define		MOF_ANALYSXCLASS_ID											MOF_CLASSIDSET(MOF_READTEXTFILECLASS_ID,		0x0431)			//!<Xファイル解析クラス
#define		MOF_CONVERTXCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0432)			//!<Xファイル変換クラス
#define		MOF_ANALYSMDLCLASS_ID										MOF_CLASSIDSET(MOF_READTEXTFILECLASS_ID,		0x0433)			//!<MDLファイル解析クラス
#define		MOF_CONVERTMDLCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0434)			//!<MDLファイル変換クラス
#define		MOF_CONVERTFBXCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0435)			//!<FBXファイル変換クラス
#define		MOF_MQOMODELCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0436)			//!<MQOファイルクラス
#define		MOF_ANALYSMQOCLASS_ID										MOF_CLASSIDSET(MOF_READTEXTFILECLASS_ID,		0x0437)			//!<MQOファイル解析クラス
#define		MOF_CONVERTMQOCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0438)			//!<MQOファイル変換クラス
#define		MOF_CONVERTPMDCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0439)			//!<PMDファイル変換クラス
#define		MOF_CONVERTPMXCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x043A)			//!<PMXファイル変換クラス
#define		MOF_CONVERTVMDCLASS_ID										MOF_CLASSIDSET(MOF_READBINARYFILECLASS_ID,		0x043B)			//!<VMDファイル変換クラス
#define		MOF_CONVERTVPDCLASS_ID										MOF_CLASSIDSET(MOF_READTEXTFILECLASS_ID,		0x043C)			//!<VPDファイル変換クラス

//スプライト変換
#define		MOF_IMAGEREADERCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0440)			//!<PSD内部画像クラス
#define		MOF_PSDREADERCLASS_ID										MOF_CLASSIDSET(MOF_IMAGEREADERCLASS_ID,			0x0441)			//!<PSD画像読み込みクラス
#define		MOF_CONVERTSPRITESTUDIOCLASS_ID								MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0442)			//!<SpriteStudioファイル変換クラス
#define		MOF_CONVERTPSDCLASS_ID										MOF_CLASSIDSET(MOF_WRITECHUNKFILECLASS_ID,		0x0443)			//!<PSDファイル変換クラス

//シェーダーエフェクト
#define		MOF_SHADEREFFECTGAUSSIANBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0450)			//!<ガウスぼかし
#define		MOF_SHADEREFFECTBRIGHTPASSCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0451)			//!<高輝度抽出
#define		MOF_SHADEREFFECTDOWNSCALE2X2CLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0452)			//!<2x2縮小
#define		MOF_SHADEREFFECTDEFERREDLIGHTINGCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0453)			//!<遅延ライティング
#define		MOF_SHADEREFFECTDEPTHOFFIELDCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0454)			//!<被写界深度シェーダー
#define		MOF_SHADEREFFECTDEPTHOUTPUTCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0455)			//!<深度出力用シェーダー
#define		MOF_SHADEREFFECTSHADOWTEXTURECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0456)			//!<シャドウマップテクスチャ作成シェーダー
#define		MOF_SHADEREFFECTSHADOWRENDERERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0457)			//!<シャドウマップの影描画シェーダー
#define		MOF_SHADEREFFECTSHADOWMAPCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0458)			//!<シャドウマップシェーダー
#define		MOF_SHADEREFFECTHDRCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0459)			//!<HDRシェーダー
#define		MOF_SHADEREFFECTDOWNSCALECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045A)			//!<汎用縮小シェーダー
#define		MOF_SHADEREFFECTSAMPLELUMINANCECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045B)			//!<輝度変換シェーダー
#define		MOF_SHADEREFFECTHDRBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045C)			//!<HDR用高輝度抽出シェーダー
#define		MOF_SHADEREFFECTTOONEDGECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045D)			//!<エッジシェーダー
#define		MOF_SHADEREFFECTTOONSHADERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045E)			//!<トゥーンレンダリングシェーダー
#define		MOF_SHADEREFFECTEDGEBASEOUTPUTCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x045F)			//!<深度＆法線出力シェーダー
#define		MOF_SHADEREFFECTCASCADEDSHADOWMAPCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0460)			//!<カスケードシャドウマップシェーダー
#define		MOF_SHADEREFFECTCASCADEVARIANCERENDERERCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0461)			//!<カスケードバリアンスシャドウマップの影描画シェーダー
#define		MOF_SHADEREFFECTSIMPLEBLURCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0462)			//!<単純ぼかしシェーダー
#define		MOF_SHADEREFFECTBUMPMAPPINGCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0463)			//!<バンプマッピングシェーダー
#define		MOF_SHADEREFFECTEDGEMASKOUTPUTCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0464)			//!<エッジマスク描画シェーダー
#define		MOF_SHADEREFFECTBLOOMCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0465)			//!<ブルームシェーダー

//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
//DirectX11グラフィックス

#define		MOF_DX11GRAPHICSCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0470)			//!<DirectX11グラフィックスクラス
#define		MOF_DX11RENDERTARGETCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0471)			//!<DirectX11描画ターゲットクラス
#define		MOF_DX11DEPTHTARGETCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0472)			//!<DirectX11深度ターゲットクラス
#define		MOF_DX11TEXTURECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0473)			//!<DirectX11テクスチャクラス
#define		MOF_DX11FONTCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0474)			//!<DirectX11フォントクラス
#define		MOF_DX11SHADERCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0475)			//!<DirectX11シェーダー
#define		MOF_DX11SHADERPASSCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0476)			//!<DirectX11シェーダーパス
#define		MOF_DX11SHADERTECHNIQUECLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0477)			//!<DirectX11シェーダーテクニック
#define		MOF_DX11SHADERBUFFERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0478)			//!<DirectX11シェーダーバッファ
#define		MOF_DX11SHADERRESOURCECLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0479)			//!<DirectX11シェーダーリソース
#define		MOF_DX11VERTEXBUFFERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047A)			//!<DirectX11頂点バッファ
#define		MOF_DX11INDEXBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047B)			//!<DirectX11インデックスバッファ
#define		MOF_DX11GEOMETRYCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047C)			//!<DirectX11ジオメトリ
#define		MOF_DX11GEOMETRYINSTANCEDCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047D)			//!<DirectX11ジオメトリ
#define		MOF_DX11MATERIALCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047E)			//!<DirectX11マテリアル
#define		MOF_DX11MESHCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047F)			//!<DirectX11メッシュクラス
#define		MOF_DX11MESHCONTAINERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0480)			//!<DirectX11メッシュコンテナクラス

#define		MOF_DX11SHADERBINDSPRITEBASECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0481)			//!<DirectX11基本スプライトシェーダーバインド
#define		MOF_DX11SHADERBINDSPRITEINSTANCEDBASECLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0482)			//!<DirectX11基本スプライトシェーダーバインド
#define		MOF_DX11SHADERBINDSPRITEINSTANCEDCOLORCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0483)			//!<DirectX11基本スプライトシェーダーバインド
#define		MOF_DX11SHADERBIND2DPRIMITIVEBASECLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0484)			//!<DirectX11基本2Dプリミティブシェーダーバインド
#define		MOF_DX11SHADERBIND3DPRIMITIVEBASECLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0485)			//!<DirectX11基本3Dプリミティブシェーダーバインド
#define		MOF_DX11SHADERBINDSKINGEOMETRYBASEBASECLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0486)			//!<DirectX11基本プリミティブシェーダーバインド
#define		MOF_DX11SHADERBINDGAUSSIANBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0487)			//!<DirectX11基本プリミティブシェーダーバインド
#define		MOF_DX11SHADERBINDDEFERREDLIGHTINGCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0488)			//!<DirectX11遅延ライティングシェーダーバインド
#define		MOF_DX11SHADERBINDDEPTHOFFIELDCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0489)			//!<DirectX11被写界深度シェーダーバインド
#define		MOF_DX11SHADERBINDSHADOWRENDERERCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048A)			//!<DirectX11シャドウマップの影描画シェーダーバインド
#define		MOF_DX11SHADERBINDSHADOWRENDERERSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048B)			//!<DirectX11シャドウマップの影描画シェーダーバインド(スキンメッシュ)
#define		MOF_DX11SHADERBINDTONEMAPCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048C)			//!<DirectX11トーンマップシェーダーバインド
#define		MOF_DX11SHADERBINDBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048D)			//!<DirectX11高輝度抽出シェーダーバインド
#define		MOF_DX11SHADERBINDHDRBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048E)			//!<DirectX11HDR用高輝度抽出シェーダーバインド
#define		MOF_DX11SHADERBINDTOONEDGECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048F)			//!<DirectX11エッジシェーダーバインド
#define		MOF_DX11SHADERBINDDEPTHOUTPUTCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0490)			//!<DirectX11深度出力シェーダーバインド
#define		MOF_DX11SHADERBINDDEPTHOUTPUTSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0491)			//!<DirectX11深度出力シェーダーバインド(スキンメッシュ用)
#define		MOF_DX11SHADERBINDTOONSHADERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0492)			//!<DirectX11トゥーンレンダリングシェーダーバインド
#define		MOF_DX11SHADERBINDTOONSHADERSKINNEDCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0493)			//!<DirectX11トゥーンレンダリングシェーダーバインド(スキンメッシュ用)
#define		MOF_DX11SHADERBINDEDGEBASEOUTPUTCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0494)			//!<DirectX11深度＆法線出力シェーダーバインド
#define		MOF_DX11SHADERBINDEDGEBASEOUTPUTSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0495)			//!<DirectX11深度＆法線出力シェーダーバインド(スキンメッシュ用)
#define		MOF_DX11SHADERBINDSIMPLEBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0496)			//!<DirectX11単純ぼかしシェーダーバインド
#define		MOF_DX11SHADERBINDCASCADEVARIANCERENDERERCLASS_ID			MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0497)			//!<DirectX11カスケードバリアンスシャドウマップの影描画シェーダーバインド
#define		MOF_DX11SHADERBINDCASCADEVARIANCERENDERERSKINNEDCLASS_ID	MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0498)			//!<DirectX11カスケードバリアンスシャドウマップの影描画シェーダーバインド(スキンメッシュ用)
#define		MOF_DX11SHADERBINDBUMPMAPPINGCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0499)			//!<DirectX11バンプマッピングシェーダーバインド
#define		MOF_DX11SHADERBINDBUMPMAPPINGSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049A)			//!<DirectX11バンプマッピングシェーダーバインド(スキンメッシュ用)
#define		MOF_DX11SHADERBINDDOWNSCALECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049B)			//!<DirectX11縮小シェーダーバインド
#define		MOF_DX11SHADERBINDBLOOMCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049C)			//!<DirectX11ブルームシェーダーバインド
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
//DirectX12グラフィックス

#define		MOF_DX12GRAPHICSCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0470)			//!<DirectX12グラフィックスクラス
#define		MOF_DX12RENDERTARGETCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0471)			//!<DirectX12描画ターゲットクラス
#define		MOF_DX12DEPTHTARGETCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0472)			//!<DirectX12深度ターゲットクラス
#define		MOF_DX12TEXTURECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0473)			//!<DirectX12テクスチャクラス
#define		MOF_DX12FONTCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0474)			//!<DirectX12フォントクラス
#define		MOF_DX12SHADERCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0475)			//!<DirectX12シェーダー
#define		MOF_DX12SHADERPASSCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0476)			//!<DirectX12シェーダーパス
#define		MOF_DX12SHADERTECHNIQUECLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0477)			//!<DirectX12シェーダーテクニック
#define		MOF_DX12SHADERBUFFERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0478)			//!<DirectX12シェーダーバッファ
#define		MOF_DX12SHADERRESOURCECLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0479)			//!<DirectX12シェーダーリソース
#define		MOF_DX12VERTEXBUFFERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047A)			//!<DirectX12頂点バッファ
#define		MOF_DX12INDEXBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047B)			//!<DirectX12インデックスバッファ
#define		MOF_DX12GEOMETRYCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047C)			//!<DirectX12ジオメトリ
#define		MOF_DX12GEOMETRYINSTANCEDCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047D)			//!<DirectX12ジオメトリ
#define		MOF_DX12MATERIALCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047E)			//!<DirectX12マテリアル
#define		MOF_DX12MESHCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x047F)			//!<DirectX12メッシュクラス
#define		MOF_DX12MESHCONTAINERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0480)			//!<DirectX12メッシュコンテナクラス

#define		MOF_DX12SHADERBINDSPRITEBASECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0481)			//!<DirectX12基本スプライトシェーダーバインド
#define		MOF_DX12SHADERBINDSPRITEINSTANCEDBASECLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0482)			//!<DirectX12基本スプライトシェーダーバインド
#define		MOF_DX12SHADERBINDSPRITEINSTANCEDCOLORCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0483)			//!<DirectX12基本スプライトシェーダーバインド
#define		MOF_DX12SHADERBIND2DPRIMITIVEBASECLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0484)			//!<DirectX12基本2Dプリミティブシェーダーバインド
#define		MOF_DX12SHADERBIND3DPRIMITIVEBASECLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0485)			//!<DirectX12基本3Dプリミティブシェーダーバインド
#define		MOF_DX12SHADERBINDSKINGEOMETRYBASEBASECLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0486)			//!<DirectX12基本プリミティブシェーダーバインド
#define		MOF_DX12SHADERBINDGAUSSIANBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0487)			//!<DirectX12基本プリミティブシェーダーバインド
#define		MOF_DX12SHADERBINDDEFERREDLIGHTINGCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0488)			//!<DirectX12遅延ライティングシェーダーバインド
#define		MOF_DX12SHADERBINDDEPTHOFFIELDCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0489)			//!<DirectX12被写界深度シェーダーバインド
#define		MOF_DX12SHADERBINDSHADOWRENDERERCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048A)			//!<DirectX12シャドウマップの影描画シェーダーバインド
#define		MOF_DX12SHADERBINDSHADOWRENDERERSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048B)			//!<DirectX12シャドウマップの影描画シェーダーバインド(スキンメッシュ)
#define		MOF_DX12SHADERBINDTONEMAPCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048C)			//!<DirectX12トーンマップシェーダーバインド
#define		MOF_DX12SHADERBINDBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048D)			//!<DirectX12高輝度抽出シェーダーバインド
#define		MOF_DX12SHADERBINDHDRBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048E)			//!<DirectX12HDR用高輝度抽出シェーダーバインド
#define		MOF_DX12SHADERBINDTOONEDGECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x048F)			//!<DirectX12エッジシェーダーバインド
#define		MOF_DX12SHADERBINDDEPTHOUTPUTCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0490)			//!<DirectX12深度出力シェーダーバインド
#define		MOF_DX12SHADERBINDDEPTHOUTPUTSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0491)			//!<DirectX12深度出力シェーダーバインド(スキンメッシュ用)
#define		MOF_DX12SHADERBINDTOONSHADERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0492)			//!<DirectX12トゥーンレンダリングシェーダーバインド
#define		MOF_DX12SHADERBINDTOONSHADERSKINNEDCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0493)			//!<DirectX12トゥーンレンダリングシェーダーバインド(スキンメッシュ用)
#define		MOF_DX12SHADERBINDEDGEBASEOUTPUTCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0494)			//!<DirectX12深度＆法線出力シェーダーバインド
#define		MOF_DX12SHADERBINDEDGEBASEOUTPUTSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0495)			//!<DirectX12深度＆法線出力シェーダーバインド(スキンメッシュ用)
#define		MOF_DX12SHADERBINDSIMPLEBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0496)			//!<DirectX12単純ぼかしシェーダーバインド
#define		MOF_DX12SHADERBINDCASCADEVARIANCERENDERERCLASS_ID			MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0497)			//!<DirectX12カスケードバリアンスシャドウマップの影描画シェーダーバインド
#define		MOF_DX12SHADERBINDCASCADEVARIANCERENDERERSKINNEDCLASS_ID	MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0498)			//!<DirectX12カスケードバリアンスシャドウマップの影描画シェーダーバインド(スキンメッシュ用)
#define		MOF_DX12SHADERBINDBUMPMAPPINGCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0499)			//!<DirectX12バンプマッピングシェーダーバインド
#define		MOF_DX12SHADERBINDBUMPMAPPINGSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049A)			//!<DirectX12バンプマッピングシェーダーバインド(スキンメッシュ用)
#define		MOF_DX12SHADERBINDDOWNSCALECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049B)			//!<DirectX12縮小シェーダーバインド
#define		MOF_DX12SHADERBINDBLOOMCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x049C)			//!<DirectX12ブルームシェーダーバインド
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
//OpenGLグラフィックス

#define		MOF_GLGRAPHICSCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A0)			//!<OpenGLグラフィックスクラス
#define		MOF_GLRENDERTARGETCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A1)			//!<OpenGL描画ターゲットクラス
#define		MOF_GLDEPTHTARGETCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A2)			//!<OpenGL深度ターゲットクラス
#define		MOF_GLTEXTURECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A3)			//!<OpenGLテクスチャクラス
#define		MOF_GLFONTCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A4)			//!<OpenGLフォントクラス
#define		MOF_GLSHADERCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A5)			//!<OpenGLシェーダー
#define		MOF_GLSHADERPASSCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A6)			//!<OpenGLシェーダーパス
#define		MOF_GLSHADERTECHNIQUECLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A7)			//!<OpenGLシェーダーテクニック
#define		MOF_GLVERTEXBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A8)			//!<OpenGL頂点バッファ
#define		MOF_GLINDEXBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04A9)			//!<OpenGLインデックスバッファ
#define		MOF_GLGEOMETRYCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04AA)			//!<OpenGLジオメトリ
#define		MOF_GLGEOMETRYINSTANCEDCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04AB)			//!<OpenGLジオメトリ
#define		MOF_GLMATERIALCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04AC)			//!<OpenGLマテリアル
#define		MOF_GLMESHCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04AD)			//!<OpenGLメッシュクラス
#define		MOF_GLMESHCONTAINERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04AE)			//!<OpenGLメッシュコンテナクラス

#define		MOF_GLSHADERBINDSPRITEBASECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B0)			//!<OpenGL基本スプライトシェーダーバインド
#define		MOF_GLSHADERBIND2DPRIMITIVEBASECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B1)			//!<OpenGL基本2Dプリミティブシェーダーバインド
#define		MOF_GLSHADERBIND3DPRIMITIVEBASECLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B2)			//!<OpenGL基本3Dプリミティブシェーダーバインド
#define		MOF_GLSHADERBINDSKINGEOMETRYBASEBASECLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B3)			//!<OpenGL基本プリミティブシェーダーバインド
#define		MOF_GLSHADERBINDGAUSSIANBLURCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B4)			//!<OpenGLガウスぼかしシェーダーバインド
#define		MOF_GLSHADERBINDBUMPMAPPINGCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B5)			//!<OpenGLバンプマッピングシェーダーバインド
#define		MOF_GLSHADERBINDBUMPMAPPINGSKINNEDCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B6)			//!<OpenGLバンプマッピングシェーダーバインド(スキンメッシュ用)
#define		MOF_GLSHADERBINDEDGEBASEOUTPUTCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B7)			//!<OpenGL深度＆法線出力シェーダーバインド
#define		MOF_GLSHADERBINDEDGEBASEOUTPUTSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B8)			//!<OpenGL深度＆法線出力シェーダーバインド(スキンメッシュ用)
#define		MOF_GLSHADERBINDTOONSHADERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04B9)			//!<OpenGLトゥーンレンダリングシェーダーバインド
#define		MOF_GLSHADERBINDTOONSHADERSKINNEDCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BA)			//!<OpenGLトゥーンレンダリングシェーダーバインド(スキンメッシュ用)
#define		MOF_GLSHADERBINDSIMPLEBLURCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BB)			//!<OpenGL単純ぼかしシェーダーバインド
#define		MOF_GLSHADERBINDSHADOWRENDERERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BC)			//!<OpenGLシャドウマップの影描画シェーダーバインド
#define		MOF_GLSHADERBINDSHADOWRENDERERSKINNEDCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BD)			//!<OpenGLシャドウマップの影描画シェーダーバインド(スキンメッシュ用)
#define		MOF_GLSHADERBINDDEPTHOUTPUTCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BE)			//!<OpenGL深度出力シェーダーバインド
#define		MOF_GLSHADERBINDDEPTHOUTPUTSKINNEDCLASS_ID					MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04BF)			//!<OpenGL深度出力シェーダーバインド(スキンメッシュ用)
#define		MOF_GLSHADERBINDDEPTHOFFIELDCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C0)			//!<OpenGL被写界深度シェーダーバインド
#define		MOF_GLSHADERBINDTOONEDGECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C1)			//!<OpenGLエッジシェーダーバインド
#define		MOF_GLSHADERBINDBRIGHTPASSCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C2)			//!<OpenGL高輝度抽出シェーダーバインド
#define		MOF_GLSHADERBINDDOWNSCALECLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C3)			//!<OpenGL縮小シェーダーバインド
#define		MOF_GLSHADERBINDHDRBRIGHTPASSCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C4)			//!<OpenGLHDR用高輝度抽出シェーダーバインド
#define		MOF_GLSHADERBINDTONEMAPCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C5)			//!<OpenGLトーンマップシェーダーバインド
#define		MOF_GLSHADERBINDBLOOMCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C6)			//!<OpenGLブルームシェーダーバインド
#define		MOF_GLSHADERBINDCASCADEVARIANCERENDERERCLASS_ID				MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C7)			//!<OpenGLカスケードバリアンスシャドウマップの影描画シェーダーバインド
#define		MOF_GLSHADERBINDCASCADEVARIANCERENDERERSKINNEDCLASS_ID		MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x04C8)			//!<OpenGLカスケードバリアンスシャドウマップの影描画シェーダーバインド(スキンメッシュ用)
//----------------------------------------------------------------------------

/*************************************************************************//*!
					サウンド関連内部ID
*//**************************************************************************/
#define		MOF_XAUDIOSOUNDCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0501)			//!<XAudio2サウンドクラス
#define		MOF_XAUDIOSOUNDBUFFERCLASS_ID								MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0502)			//!<XAudio2サウンドバッファクラス
#define		MOF_XAUDIOSTREAMINGSOUNDBUFFERCLASS_ID						MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0503)			//!<XAudio2ストリーミングサウンドバッファクラス

#define		MOF_MP3FILECLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0511)			//!<ＭＰ３ファイルデコード用クラス
#define		MOF_UWPSTREAMCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0512)			//!<ＵＷＰファイルデコード用クラス

#define		MOF_SLSOUNDCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0520)			//!<OpenSLサウンドクラス
#define		MOF_SLSOUNDBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0501)			//!<OpenSLサウンドバッファクラス
#define		MOF_SLSTREAMINGSOUNDBUFFERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0502)			//!<OpenSLストリーミングサウンドバッファクラス

#define		MOF_ALSOUNDCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0530)			//!<OpenALサウンドクラス
#define		MOF_ALSOUNDBUFFERCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0531)			//!<OpenALサウンドバッファクラス
#define		MOF_ALSTREAMINGSOUNDBUFFERCLASS_ID							MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0532)			//!<OpenALストリーミングサウンドバッファクラス

/*************************************************************************//*!
					インプット関連内部ID
*//**************************************************************************/
#define		MOF_DXINPUTCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0601)			//!<DirectInputクラス
#define		MOF_UWPINPUTCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0601)			//!<UWPInputクラス
#define		MOF_DXINPUTGAMEPADCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0602)			//!<DirectInputゲームパッドクラス
#define		MOF_XINPUTGAMEPADCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0603)			//!<XInputゲームパッドクラス
#define		MOF_UWPGAMEPADCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0604)			//!<UWPゲームパッドクラス

#define		MOF_ANDROIDINPUTCLASS_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0610)			//!<Androidクラス

/*************************************************************************//*!
					あたり判定関連内部ID
*//**************************************************************************/
#define		MOF_RECTANGLECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0801)			//!<矩形クラス
#define		MOF_CIRCLECLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0802)			//!<円クラス
#define		MOF_AABBCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0803)			//!<箱(AABB)クラス
#define		MOF_OBBCLASS_ID												MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0804)			//!<箱(OBB)クラス
#define		MOF_SPHERECLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0805)			//!<球クラス
#define		MOF_CAPSULECLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0806)			//!<カプセルクラス
#define		MOF_RAY3DCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0807)			//!<3Dレイクラス

/*************************************************************************//*!
					ネットワーク関連内部ID
*//**************************************************************************/
#define		MOF_NETWORKCLASS_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0901)			//!<ネットワーククラス
#define		MOF_UDPSOCKETCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0902)			//!<UDPソケットクラス

/*************************************************************************//*!
					ムービー関連内部ID
*//**************************************************************************/
#define		MOF_DSHOWMOVIECLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0A01)			//!<DirectShow動画クラス

/*************************************************************************//*!
					互換性のためのＩＤ
*//**************************************************************************/
#define		MOF_MBSOBJECTBASE_ID										MOF_CLASSIDSET(MOF_DYNAMICARRAYCLASS_ID,		0x0B01)			//!<基礎オブジェクト
#define		MOF_MBSEFFECTMEMORYLIST_ID									MOF_CLASSIDSET(MOF_DYNAMICARRAYCLASS_ID,		0x0B02)			//!<エフェクトメモリリスト
#define		MOF_MBSEFFECTRENDERLIST_ID									MOF_CLASSIDSET(MOF_DYNAMICARRAYCLASS_ID,		0x0B03)			//!<エフェクト描画リスト
#define		MOF_MBSEFFECTOBJECT_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B04)			//!<エフェクトオブジェクト
#define		MOF_MBSEFFECTCONTAINER_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B05)			//!<エフェクトコンテナ
#define		MOF_MBSPARTICLE_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B06)			//!<パーティクル
#define		MOF_MBSEFFECT_ID											MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B07)			//!<エフェクト
#define		MOF_MBSEFFECTCONTROLLER_ID									MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B08)			//!<エフェクトコントローラー
#define		MOF_MBSSCENEOBJECT_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B09)			//!<シーンオブジェクト
#define		MOF_MBSSCENERESOURCE_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B0A)			//!<シーンリソース
#define		MOF_MBSACTIVECAMERA_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0B0B)			//!<カメラ

/*************************************************************************//*!
					外部定義用一時ＩＤ
*//**************************************************************************/
#define		MOF_TEMPORARYCLASS_ID										MOF_CLASSIDSET(MOF_CLASSBASEINTERFACE,			0x0001)			//!<外部用一時ID

#endif

//[EOF]