#ifdef SHADER_INCLUDE

const char* g_BumpMappingSkinned_VS =
"attribute vec4 pos;\n"
"attribute vec3 normal;\n"
"attribute vec3 Tangent;\n"
"attribute vec3 Binormal;\n"
"attribute vec4 weight;\n"
"attribute vec4 bindex;\n"
"attribute vec2 Tex;\n"
"attribute vec4 color;\n"
"varying vec2 OUV;\n"
"varying vec3 ONORMAL;\n"
"varying vec3 OTANGENT;\n"
"varying vec3 OBINORMAL;\n"
"varying vec3 OEYE;\n"
"varying vec4 OVCOL;\n"
"uniform vec4 mtxWorld[3 * 128];\n"
"uniform mat4 mtxView;\n"
"uniform mat4 mtxProj;\n"
"uniform vec4 vecViewPos;\n"
"uniform vec4 colRevise;\n"
"uniform vec4 CoordsRevise;\n"
"void main(){\n"
	"vec4 tPos = vec4(0.0, 0.0, 0.0, 1.0);\n"
	"vec3 norm = vec3(0.0, 0.0, 0.0);\n"
	"vec3 t = vec3(0.0, 0.0, 0.0);\n"
	"vec3 b = vec3(0.0, 0.0, 0.0);\n"
	"int idx;\n"
	"idx = int(bindex[0]) * 3;\n"
	"tPos.x += dot( pos, mtxWorld[idx + 0] ) * weight[0];\n"
	"tPos.y += dot( pos, mtxWorld[idx + 1] ) * weight[0];\n"
	"tPos.z += dot( pos, mtxWorld[idx + 2] ) * weight[0];\n"
	"norm.x += dot( normal, mtxWorld[idx + 0].xyz ) * weight[0];\n"
	"norm.y += dot( normal, mtxWorld[idx + 1].xyz ) * weight[0];\n"
	"norm.z += dot( normal, mtxWorld[idx + 2].xyz ) * weight[0];\n"
	"t.x += dot( Tangent, mtxWorld[idx + 0].xyz ) * weight[0];\n"
	"t.y += dot( Tangent, mtxWorld[idx + 1].xyz ) * weight[0];\n"
	"t.z += dot( Tangent, mtxWorld[idx + 2].xyz ) * weight[0];\n"
	"b.x += dot( Binormal, mtxWorld[idx + 0].xyz ) * weight[0];\n"
	"b.y += dot( Binormal, mtxWorld[idx + 1].xyz ) * weight[0];\n"
	"b.z += dot( Binormal, mtxWorld[idx + 2].xyz ) * weight[0];\n"
	"idx = int(bindex[1]) * 3;\n"
	"tPos.x += dot( pos, mtxWorld[idx + 0] ) * weight[1];\n"
	"tPos.y += dot( pos, mtxWorld[idx + 1] ) * weight[1];\n"
	"tPos.z += dot( pos, mtxWorld[idx + 2] ) * weight[1];\n"
	"norm.x += dot( normal, mtxWorld[idx + 0].xyz ) * weight[1];\n"
	"norm.y += dot( normal, mtxWorld[idx + 1].xyz ) * weight[1];\n"
	"norm.z += dot( normal, mtxWorld[idx + 2].xyz ) * weight[1];\n"
	"t.x += dot( Tangent, mtxWorld[idx + 0].xyz ) * weight[1];\n"
	"t.y += dot( Tangent, mtxWorld[idx + 1].xyz ) * weight[1];\n"
	"t.z += dot( Tangent, mtxWorld[idx + 2].xyz ) * weight[1];\n"
	"b.x += dot( Binormal, mtxWorld[idx + 0].xyz ) * weight[1];\n"
	"b.y += dot( Binormal, mtxWorld[idx + 1].xyz ) * weight[1];\n"
	"b.z += dot( Binormal, mtxWorld[idx + 2].xyz ) * weight[1];\n"
	"idx = int(bindex[2]) * 3;\n"
	"tPos.x += dot( pos, mtxWorld[idx + 0] ) * weight[2];\n"
	"tPos.y += dot( pos, mtxWorld[idx + 1] ) * weight[2];\n"
	"tPos.z += dot( pos, mtxWorld[idx + 2] ) * weight[2];\n"
	"norm.x += dot( normal, mtxWorld[idx + 0].xyz ) * weight[2];\n"
	"norm.y += dot( normal, mtxWorld[idx + 1].xyz ) * weight[2];\n"
	"norm.z += dot( normal, mtxWorld[idx + 2].xyz ) * weight[2];\n"
	"t.x += dot( Tangent, mtxWorld[idx + 0].xyz ) * weight[2];\n"
	"t.y += dot( Tangent, mtxWorld[idx + 1].xyz ) * weight[2];\n"
	"t.z += dot( Tangent, mtxWorld[idx + 2].xyz ) * weight[2];\n"
	"b.x += dot( Binormal, mtxWorld[idx + 0].xyz ) * weight[2];\n"
	"b.y += dot( Binormal, mtxWorld[idx + 1].xyz ) * weight[2];\n"
	"b.z += dot( Binormal, mtxWorld[idx + 2].xyz ) * weight[2];\n"
	"idx = int(bindex[3]) * 3;\n"
	"tPos.x += dot( pos, mtxWorld[idx + 0] ) * weight[3];\n"
	"tPos.y += dot( pos, mtxWorld[idx + 1] ) * weight[3];\n"
	"tPos.z += dot( pos, mtxWorld[idx + 2] ) * weight[3];\n"
	"norm.x += dot( normal, mtxWorld[idx + 0].xyz ) * weight[3];\n"
	"norm.y += dot( normal, mtxWorld[idx + 1].xyz ) * weight[3];\n"
	"norm.z += dot( normal, mtxWorld[idx + 2].xyz ) * weight[3];\n"
	"mat4 mtxVP = mtxView * mtxProj;\n"
	"gl_Position = tPos * mtxVP;\n"
	"ONORMAL = normalize( norm );\n"
	"OTANGENT = normalize( t );\n"
	"OBINORMAL = normalize( b );\n"
	"OEYE = normalize( tPos.xyz - vecViewPos.xyz );\n"
	"OVCOL = color * colRevise;\n"
	"OUV = Tex + CoordsRevise.xy;\n"
"}\n";

const char* g_BumpMappingSkinned_PS =
"precision mediump float;\n"
"varying vec2 OUV;\n"
"varying vec3 ONORMAL;\n"
"varying vec3 OTANGENT;\n"
"varying vec3 OBINORMAL;\n"
"varying vec3 OEYE;\n"
"varying vec4 OVCOL;\n"
"uniform vec4 matDiffuse;\n"
"uniform vec4 matAmbient;\n"
"uniform vec4 matSpeculer;\n"
"uniform vec4 matEmissive;\n"
"uniform float matPower;\n"
"uniform vec3 litDirection;\n"
"uniform vec4 litDiffuse;\n"
"uniform vec4 litAmbient;\n"
"uniform vec4 litSpeculer;\n"
"uniform sampler2D txDiffuse;\n"
"uniform sampler2D txNormalTex;\n"
"void main(){\n"
	"vec3 Normal = 2.0f * texture2D( txNormalTex, OUV).rgb - 1.0f;\n"
	"Normal = vec3(\n"
		"dot(vec3(OTANGENT.x,OBINORMAL.x,ONORMAL.x),Normal),\n"
		"dot(vec3(OTANGENT.y,OBINORMAL.y,ONORMAL.y),Normal),\n"
		"dot(vec3(OTANGENT.z,OBINORMAL.z,ONORMAL.z),Normal)\n"
	");\n"
	"vec3 amb = litAmbient.xyz * matAmbient.xyz;\n"
	"float l = max( 0.0f, dot( Normal, -litDirection ) );\n"
	"vec3 diff = l * litDiffuse.xyz * matDiffuse.xyz;\n"
	"vec4 LP = vec4( clamp( matEmissive.xyz + amb + diff, 0.0, 1.0 ) , matDiffuse.w ) * OVCOL;\n"
	"vec4 ocol = LP * texture2D( txDiffuse, OUV);\n"
	"vec3 R = reflect( OEYE, Normal );\n"
	"ocol.xyz += litSpeculer.xyz * matSpeculer.xyz * pow( abs( max( 0 , dot( R, -litDirection ) ) ) , matPower );\n"
	"gl_FragColor = ocol;\n"
"}\n";


#else
extern const char* g_BumpMappingSkinned_VS;
extern const char* g_BumpMappingSkinned_PS;
#endif
